export const testData = {
  gridNoBingo: [
    { de: "Fahrrad", en: "bike", flipped: false },
    { de: "Bus", en: "bus", flipped: false },
    { de: "Auto", en: "car", flipped: false },
    { de: "Flugzeug", en: "plane", flipped: false },
    { de: "Zug", en: "train", flipped: true },
    { de: "Motarrad", en: "motorbike", flipped: false },
    { de: "Strasse", en: "street", flipped: false },
    { de: "Ampel", en: "trafficlight", flipped: true },
    { de: "Mama braucht Kaffee", en: "coffeeshop", flipped: false },
  ],
  gridNoBingo2: [
    { de: "Fahrrad", en: "bike", flipped: false },
    { de: "Bus", en: "bus", flipped: true },
    { de: "Auto", en: "car", flipped: false },
    { de: "Flugzeug", en: "plane", flipped: false },
    { de: "Zug", en: "train", flipped: false },
    { de: "Motarrad", en: "motorbike", flipped: false },
    { de: "Strasse", en: "street", flipped: false },
    { de: "Ampel", en: "trafficlight", flipped: true },
    { de: "Mama braucht Kaffee", en: "coffeeshop", flipped: false },
  ],
  gridNoBingo3: [
    { de: "Fahrrad", en: "bike", flipped: true },
    { de: "Bus", en: "bus", flipped: false },
    { de: "Auto", en: "car", flipped: true },
    { de: "Flugzeug", en: "plane", flipped: false },
    { de: "Zug", en: "train", flipped: true },
    { de: "Motarrad", en: "motorbike", flipped: false },
    { de: "Strasse", en: "street", flipped: false },
    { de: "Ampel", en: "trafficlight", flipped: false },
    { de: "Mama braucht Kaffee", en: "coffeeshop", flipped: false },
  ],
  gridNoBingo4: [
    { de: "Fahrrad", en: "bike", flipped: false },
    { de: "Bus", en: "bus", flipped: false },
    { de: "Auto", en: "car", flipped: false },
    { de: "Flugzeug", en: "plane", flipped: false },
    { de: "Zug", en: "train", flipped: true },
    { de: "Motarrad", en: "motorbike", flipped: false },
    { de: "Strasse", en: "street", flipped: true },
    { de: "Ampel", en: "trafficlight", flipped: true },
    { de: "Mama braucht Kaffee", en: "coffeeshop", flipped: false },
  ],
  gridBingo1: [
    { de: "Fahrrad", en: "bike", flipped: true },
    { de: "Bus", en: "bus", flipped: true },
    { de: "Auto", en: "car", flipped: true },
    { de: "Flugzeug", en: "plane", flipped: false },
    { de: "Zug", en: "train", flipped: true },
    { de: "Motarrad", en: "motorbike", flipped: false },
    { de: "Strasse", en: "street", flipped: true },
    { de: "Ampel", en: "trafficlight", flipped: true },
    { de: "Mama braucht Kaffee", en: "coffeeshop", flipped: false },
  ],
  gridBingo2: [
    { de: "Fahrrad", en: "bike", flipped: false },
    { de: "Bus", en: "bus", flipped: false },
    { de: "Auto", en: "car", flipped: false },
    { de: "Flugzeug", en: "plane", flipped: true },
    { de: "Zug", en: "train", flipped: true },
    { de: "Motarrad", en: "motorbike", flipped: false },
    { de: "Strasse", en: "street", flipped: true },
    { de: "Ampel", en: "trafficlight", flipped: true },
    { de: "Mama braucht Kaffee", en: "coffeeshop", flipped: true },
  ],
};
